fix: Root directory input is valid!
for github action:
Error: The path for one of the files in artifact is not valid: /test_allocations_hallucinating-0305-20:12:08/0-True.json. Contains the following character:  Colon :

Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n

The following characters are not allowed in files that are uploaded due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.

Signed-off-by: Paul Zabelin <paulzabelin@artium.ai>