cleanup code, improve folder names (#9)
* fix: better folder names

update unique ID format in reporter.py

Signed-off-by: Paul Zabelin <paulzabelin@artium.ai>

* fix: can't find references to reporter

remove extra packages in test,
rename test files for clarity

Signed-off-by: Paul Zabelin <paulzabelin@artium.ai>

* fix: remove unused import from test_allocations_hallucinating.py

Signed-off-by: Paul Zabelin <paulzabelin@artium.ai>

* fix: unknown reference

Signed-off-by: Paul Zabelin <paulzabelin@artium.ai>

* Revert "fix: unknown reference"

This reverts commit 041fb730c9224728d15ac8b428b58de2d5ff4601.

* fix: Root directory input is valid!

for github action:
Error: The path for one of the files in artifact is not valid: /test_allocations_hallucinating-0305-20:12:08/0-True.json. Contains the following character:  Colon :

Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n

The following characters are not allowed in files that are uploaded due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.

Signed-off-by: Paul Zabelin <paulzabelin@artium.ai>

---------

Signed-off-by: Paul Zabelin <paulzabelin@artium.ai>
Co-authored-by: Paul Zabelin <paulz@users.noreply.github.com>